# You can use a Docker image from Docker Hub or your own container registry
image: golang:1.6
   
pipelines:
  default:
    - step:
        script:
          - ls -al
          - export GOPATH=$HOME/gopath
          - export PATH=$HOME/gopath/bin:$PATH
          - env
          - mkdir -p $HOME/gopath/src/github.com/ocean/commerce-yt-api
          - cp -R $(pwd)/ $HOME/gopath/src/github.com/ocean/commerce-yt-api/
          # - export BUILD_DIR=$HOME/gopath/src/github.com/ocean/commerce-yt-api
          - cd $HOME/gopath/src/github.com/ocean/commerce-yt-api
          - echo "Installing dependencies..."
          - go get -v github.com/tools/godep
          - godep go install -v ./cmd/commerce-yt-api/
          - go install -v ./cmd/wakeup/
          - godep get -v github.com/stretchr/testify
          - echo "Running tests..."
          - go test -v ./cmd/commerce-yt-api/