# You can use a Docker image from Docker Hub or your own container registry
image: golang:1.7
   
pipelines:
  default:
    - step:
        script:
          - ls -al
          - export GOPATH=$HOME/gopath
          - export PATH=$HOME/gopath/bin:$PATH
          - mkdir -p $HOME/gopath/src/github.com/ocean/commerce-yt-api
          - cp -v -R . $HOME/gopath/src/github.com/ocean/commerce-yt-api
          # - export BUILD_DIR=$HOME/gopath/src/github.com/ocean/commerce-yt-api
          - cd $HOME/gopath/src/github.com/ocean/commerce-yt-api
          - go env
          - env
          - echo "Installing dependencies..."
          - pwd && go install -v github.com/golang/dep/cmd/dep
          - ls -al
          - pwd && dep ensure
          - echo "Running tests..."
          - go test -v ./cmd/commerce-yt-api/
